### ISSUE TITLE
Default group and default action setting wit Action_Group controller

### ISSUE THREAD

**Issue by megawebmaster** [zyxist/Trinity#1]
There is a problem with setting default group and action from configuration - Trinity sets them to empty string, so using no parameters to url causes exception _"A controller error occured: input data validation error"._
Using some parameters, i.e. only group (for a Action_Group controller) causes exception: _"A controller error occured: the requested controller action has not been found."._

**Comment by zyxist** [comment]
Cannot reproduce the problem. I think it may lie in your mod_rewrite settings or something like that, because it doesn't occur even in a script you claim it occurs. You have to provide more information.

**Comment by megawebmaster** [comment]
OK, nevermind, problem was in config.ini file, even in a script I've claimed it occurs. I've provided more information on private chat.
